---
language: ruby
services:
    - docker
branches:
    only:
        - master
matrix:
    include:
        - env: NSVER=7 IMAGE_REPO=nethserver/makerpms
        - env: NSVER=6 IMAGE_REPO=nethserver/makerpms
env:
    global:
        - NSLATEST=7
        - >
            EVARS="
            -e DEST_ID
            -e TRAVIS_BRANCH
            -e TRAVIS_BUILD_ID
            -e TRAVIS_PULL_REQUEST_BRANCH
            -e TRAVIS_PULL_REQUEST
            -e TRAVIS_REPO_SLUG
            -e TRAVIS_TAG
            -e NSVER
            -e VERSIONS_PACK
            -e STAGES_PACK
            -e UPLOAD_DEST
            "

script:
    - bash -x travis/build-container.sh
